export const topicsData = [
  {
    title: "Algorithms",
    status:'pending',
    subTopics: [
      { name: 'Sorting Algorithms', leetCode: 'https://leetcode.com/tag/sorting/', youtube: 'https://www.youtube.com/results?search_query=sorting+algorithms', article: 'https://www.geeksforgeeks.org/sorting-algorithms/', level: 'EASY', status: 'Done' },
      { name: 'Searching Algorithms', leetCode: 'https://leetcode.com/tag/searching/', youtube: 'https://www.youtube.com/results?search_query=searching+algorithms', article: 'https://www.geeksforgeeks.org/searching-algorithms/', level: 'MEDIUM', status: 'Pending' },
      { name: 'Dynamic Programming', leetCode: 'https://leetcode.com/tag/dynamic-programming/', youtube: 'https://www.youtube.com/results?search_query=dynamic+programming', article: 'https://www.geeksforgeeks.org/dynamic-programming/', level: 'HARD', status: 'Pending' },
      { name: 'Graph Algorithms', leetCode: 'https://leetcode.com/tag/graph/', youtube: 'https://www.youtube.com/results?search_query=graph+algorithms', article: 'https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/', level: 'MEDIUM', status: 'Done' },
      { name: 'Greedy Algorithms', leetCode: 'https://leetcode.com/tag/greedy/', youtube: 'https://www.youtube.com/results?search_query=greedy+algorithms', article: 'https://www.geeksforgeeks.org/greedy-algorithms/', level: 'EASY', status: 'Done' },
      { name: 'Backtracking', leetCode: 'https://leetcode.com/tag/backtracking/', youtube: 'https://www.youtube.com/results?search_query=backtracking', article: 'https://www.geeksforgeeks.org/backtracking-algorithms/', level: 'HARD', status: 'Pending' },
    ],
  },
  {
    title: "Data Structures",
    status:'pending',
    subTopics: [
      { name: 'Arrays', leetCode: 'https://leetcode.com/tag/array/', youtube: 'https://www.youtube.com/results?search_query=arrays', article: 'https://www.geeksforgeeks.org/array-data-structure/', level: 'EASY', status: 'Done' },
      { name: 'Linked Lists', leetCode: 'https://leetcode.com/tag/linked-list/', youtube: 'https://www.youtube.com/results?search_query=linked+list', article: 'https://www.geeksforgeeks.org/linked-list-data-structure/', level: 'MEDIUM', status: 'Pending' },
      { name: 'Stacks', leetCode: 'https://leetcode.com/tag/stack/', youtube: 'https://www.youtube.com/results?search_query=stack+data+structure', article: 'https://www.geeksforgeeks.org/stack-data-structure/', level: 'EASY', status: 'Done' },
      { name: 'Queues', leetCode: 'https://leetcode.com/tag/queue/', youtube: 'https://www.youtube.com/results?search_query=queue+data+structure', article: 'https://www.geeksforgeeks.org/queue-data-structure/', level: 'MEDIUM', status: 'Pending' },
      { name: 'Trees', leetCode: 'https://leetcode.com/tag/tree/', youtube: 'https://www.youtube.com/results?search_query=tree+data+structure', article: 'https://www.geeksforgeeks.org/tree-data-structure/', level: 'HARD', status: 'Pending' },
      { name: 'Graphs', leetCode: 'https://leetcode.com/tag/graph/', youtube: 'https://www.youtube.com/results?search_query=graph+data+structure', article: 'https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/', level: 'HARD', status: 'Done' },
    ],
  },
  {
    title: "Databases",
    status:'pending',
    subTopics: [
      { name: 'SQL Basics', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=sql+basics', article: 'https://www.geeksforgeeks.org/sql-tutorial/', level: 'EASY', status: 'Done' },
      { name: 'Joins', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=sql+joins', article: 'https://www.geeksforgeeks.org/sql-join/', level: 'MEDIUM', status: 'Pending' },
      { name: 'Indexes', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=sql+indexes', article: 'https://www.geeksforgeeks.org/indexing-in-databases-set-1/', level: 'MEDIUM', status: 'Pending' },
      { name: 'Normalization', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=database+normalization', article: 'https://www.geeksforgeeks.org/database-normalization/', level: 'HARD', status: 'Done' },
      { name: 'Transactions', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=database+transactions', article: 'https://www.geeksforgeeks.org/transaction-management-in-dbms/', level: 'HARD', status: 'Pending' },
      { name: 'NoSQL Databases', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=nosql+databases', article: 'https://www.geeksforgeeks.org/introduction-to-nosql-database/', level: 'MEDIUM', status: 'Done' },
    ],
  },
  {
    title: "Machine Learning",
    status:'pending',
    subTopics: [
      { name: 'Linear Regression', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=linear+regression', article: 'https://www.geeksforgeeks.org/linear-regression/', level: 'EASY', status: 'Pending' },
      { name: 'Logistic Regression', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=logistic+regression', article: 'https://www.geeksforgeeks.org/logistic-regression/', level: 'MEDIUM', status: 'Done' },
      { name: 'Decision Trees', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=decision+trees', article: 'https://www.geeksforgeeks.org/decision-tree/', level: 'MEDIUM', status: 'Pending' },
      { name: 'Random Forest', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=random+forest', article: 'https://www.geeksforgeeks.org/random-forest/', level: 'HARD', status: 'Pending' },
      { name: 'SVM', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=svm', article: 'https://www.geeksforgeeks.org/support-vector-machine/', level: 'HARD', status: 'Done' },
      { name: 'K-Means Clustering', leetCode: '#', youtube: 'https://www.youtube.com/results?search_query=k+means+clustering', article: 'https://www.geeksforgeeks.org/k-means-clustering/', level: 'MEDIUM', status: 'Pending' },
    ],
  },
  {
    title: "Operation Systems",
    status:'pending',
    subTopics: [
      { name: 'Processes', leetCode: '#', youtube: '#', article: '#', level: 'EASY', status: 'Pending' },
      { name: 'Threads', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'Scheduling', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Deadlocks', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Memory Management', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'File Systems', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
    ],
  },
  {
    title: "Networks",
    status:'pending',
    subTopics: [
      { name: 'OSI Model', leetCode: '#', youtube: '#', article: '#', level: 'EASY', status: 'Pending' },
      { name: 'TCP/IP', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'UDP', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'Routing', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Switching', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Network Security', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
    ],
  },
  {
    title: "Mathematics",
    status:'pending',
    subTopics: [
      { name: 'Probability', leetCode: '#', youtube: '#', article: '#', level: 'EASY', status: 'Pending' },
      { name: 'Combinatorics', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'Linear Algebra', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'Calculus', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Discrete Math', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Number Theory', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
    ],
  },
  {
    title: "Software Engineering",
    status:'pending',
    subTopics: [
      { name: 'SDLC', leetCode: '#', youtube: '#', article: '#', level: 'EASY', status: 'Pending' },
      { name: 'Agile Methodology', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'UML Diagrams', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'Design Patterns', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Requirement Analysis', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Testing & QA', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
    ],
  },
  {
    title: "Web Development",
    status:'pending',
    subTopics: [
      { name: 'HTML', leetCode: '#', youtube: '#', article: '#', level: 'EASY', status: 'Done' },
      { name: 'CSS', leetCode: '#', youtube: '#', article: '#', level: 'EASY', status: 'Done' },
      { name: 'JavaScript', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'React', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'Next.js', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Node.js', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
    ],
  },
  {
    title: "Cloud Computing",
    status:'pending',
    subTopics: [
      { name: 'AWS', leetCode: '#', youtube: '#', article: '#', level: 'EASY', status: 'Pending' },
      { name: 'Azure', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'GCP', leetCode: '#', youtube: '#', article: '#', level: 'MEDIUM', status: 'Pending' },
      { name: 'Cloud Security', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Serverless', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
      { name: 'Containers & Kubernetes', leetCode: '#', youtube: '#', article: '#', level: 'HARD', status: 'Pending' },
    ],
  },
];
